# Update dependencies

version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "07:00"
  labels:
  - "dependencies"
  - "automerge"
  reviewers:
  - "Nserbin"
