# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
    labels:
      - "dependencies"
      - "terraform"
      - "automerge"
    commit-message:
      prefix: "chore(deps): update Terraform providers"
    reviewers:
      - "Nserbin"
