name: Export Secrets

on:
  workflow_dispatch:

jobs:
  export-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Export secret as env
      run: echo "$secret" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
      env: 
        secret: ${{ toJson(secrets) }}
        
    - name: Export vars as env
      run: echo "$var" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV 
      env:
        var: ${{ toJson(vars) }}
        
    - name: Write secrets to file
      run: |
        echo "$secret" | jq -r 'to_entries[] | "\(.key)=\(.value)"' > secrets.txt
      env: 
        secret: ${{ toJson(secrets) }}

    - name: Write vars to file
      run: |
        echo "$var" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> secrets.txt
      env:
        var: ${{ toJson(vars) }}

    - name: Upload secrets artifact
      uses: actions/upload-artifact@v2
      with:
        name: secrets
        path: secrets.txt
