name: Checking Terraform Code

on:
  push:
    branches:
      - main
      - new-test
    tags:
    - "*"

permissions:
  contents: write
  pull-requests: write

jobs:
  tf_init:
    uses: NSerbin/gh-pipelines/.github/workflows/tf-init.yml@new-way-to-deploy
    with:
      terraform_version: 1.12.2
    secrets: inherit
  tf_check:
    uses: NSerbin/gh-pipelines/.github/workflows/tf-checks.yml@new-way-to-deploy
    needs: tf_init
    with:
      terraform_version: 1.12.2
    secrets: inherit
  tf_lint:
    uses: NSerbin/gh-pipelines/.github/workflows/linter.yml@new-way-to-deploy
    needs: tf_check
    with:
      tflint-version: "v0.58.0"
      language: terraform
      linter: true
    secrets: inherit