name: Checking Terraform Code

on:
  push:
    branches:
      - main
      - test
    tags:
    - "*"

permissions:
  contents: read
  pull-requests: write

# jobs:
#   tf_checks:
#     uses: NSerbin/gh-pipelines/.github/workflows/tf-checks.yml@main
#     with:
#       terraform_version: 1.8.3
#     secrets: inherit

name: Checking Terraform Code

on:
  push:
    branches:
      - main
      - test
    tags:
      - "*"

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform_checks:
    name: Terraform Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Install gomplate
        run: |
          curl -Lo gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.11.3/gomplate_linux-amd64
          chmod +x gomplate
          sudo mv gomplate /usr/local/bin/

      - name: Export All Secrets as Environment Variables
        run: |
          export CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}
          export CF_ACCOUNT=${{ secrets.CF_ACCOUNT }}
          export NS_EMAIL=${{ secrets.NS_EMAIL }}
          export NS_HELP_EMAIL=${{ secrets.NS_HELP_EMAIL }}
          export NS_CONTACT_EMAIL=${{ secrets.NS_CONTACT_EMAIL }}
          export NS_URL=${{ secrets.NS_URL }}
          export NS_GH_URL=${{ secrets.NS_GH_URL }}
          export RPI_TOKEN=${{ secrets.RPI_TOKEN }}
          export SENDGRID_EM_NAME_1=${{ secrets.SENDGRID_EM_NAME_1 }}
          export SENDGRID_EM_VALUE=${{ secrets.SENDGRID_EM_VALUE }}
          export SENDGRID_EM_NAME_2=${{ secrets.SENDGRID_EM_NAME_2 }}
          export SENDGRID_EM_NAME_3=${{ secrets.SENDGRID_EM_NAME_3 }}
          export SENDGRID_EM_NAME_4=${{ secrets.SENDGRID_EM_NAME_4 }}
          export SENDGRID_URL_NAME_1=${{ secrets.SENDGRID_URL_NAME_1 }}
          export SENDGRID_URL_NAME_2=${{ secrets.SENDGRID_URL_NAME_2 }}
          export SENDGRID_URL_NAME_3=${{ secrets.SENDGRID_URL_NAME_3 }}
          export SENDGRID_URL_NAME_4=${{ secrets.SENDGRID_URL_NAME_4 }}
          export SENDGRID_URL_NAME_5=${{ secrets.SENDGRID_URL_NAME_5 }}
          export SENDGRID_URL_NAME_6=${{ secrets.SENDGRID_URL_NAME_6 }}
          export SENDGRID_NAME=${{ secrets.SENDGRID_NAME }}
          export SENDGRID_DOMAINKEY_NAME_1=${{ secrets.SENDGRID_DOMAINKEY_NAME_1 }}
          export SENDGRID_DOMAINKEY_NAME_2=${{ secrets.SENDGRID_DOMAINKEY_NAME_2 }}
          export SENDGRID_DOMAINKEY_VALUE_1=${{ secrets.SENDGRID_DOMAINKEY_VALUE_1 }}
          export SENDGRID_DOMAINKEY_VALUE_2=${{ secrets.SENDGRID_DOMAINKEY_VALUE_2 }}
          export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          export GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}
          export GH_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }}
          export GRAFANA_URL=${{ secrets.GRAFANA_URL }}
          export GRAFANA_DOMAIN=${{ secrets.GRAFANA_DOMAIN }}
          export CADVISOR_URL=${{ secrets.CADVISOR_URL }}
          export CADVISOR_DOMAIN=${{ secrets.CADVISOR_DOMAIN }}
          export PROMETHEUS_URL=${{ secrets.PROMETHEUS_URL }}
          export PROMETHEUS_DOMAIN=${{ secrets.PROMETHEUS_DOMAIN }}
          export FRESHRSS_URL=${{ secrets.FRESHRSS_URL }}
          export FRESHRSS_DOMAIN=${{ secrets.FRESHRSS_DOMAIN }}
          export HOMEPAGE_URL=${{ secrets.HOMEPAGE_URL }}
          export HOMEPAGE_DOMAIN=${{ secrets.HOMEPAGE_DOMAIN }}
          export N8N_URL=${{ secrets.N8N_URL }}
          export N8N_DOMAIN=${{ secrets.N8N_DOMAIN }}
          export FILEBROWSER_URL=${{ secrets.FILEBROWSER_URL }}
          export FILEBROWSER_DOMAIN=${{ secrets.FILEBROWSER_DOMAIN }}
          export REMMINA_URL=${{ secrets.REMMINA_URL }}
          export REMMINA_DOMAIN=${{ secrets.REMMINA_DOMAIN }}
          export UPTIMEKUMA_URL=${{ secrets.UPTIMEKUMA_URL }}
          export UPTIMEKUMA_DOMAIN=${{ secrets.UPTIMEKUMA_DOMAIN }}
          export PORTAINER_URL=${{ secrets.PORTAINER_URL }}
          export PORTAINER_DOMAIN=${{ secrets.PORTAINER_DOMAIN }}
          export PIHOLE_URL=${{ secrets.PIHOLE_URL }}
          export PIHOLE_DOMAIN=${{ secrets.PIHOLE_DOMAIN }}
          export BITWARDEN_URL=${{ secrets.BITWARDEN_URL }}
          export BITWARDEN_DOMAIN=${{ secrets.BITWARDEN_DOMAIN }}
          export BITWARDEN_ADMIN_DOMAIN=${{ secrets.BITWARDEN_ADMIN_DOMAIN }}

      - name: Substitute Environment Variables with gomplate
        run: |
          find . -name "*.tf" -exec gomplate -d env=env:// -f {} -o {} \;

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -diff -write=true
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: true
