name: Checking Terraform Code

on:
  push:
    branches:
      - main
      - test
    tags:
    - "*"

permissions:
  contents: write
  pull-requests: write

jobs:
  tf_check:
    uses: NSerbin/gh-pipelines/.github/workflows/tf-checks.yml@main
    with:
      terraform_version: 1.8.3
    secrets: inherit

